const categories = [
  "Entertainment",
  "Food/Drink",
  "Electronics",
  "Daily Needs",
  "Fashion",
  "Shopping",
  "Bills",
  "Gifts",
  "Salary",
  "Transfer",
  "Business",
  "Investment",
  "Education",
  "Self-improvement",
  "Family",
  "Health",
  "Other Income",
  "Other Expense",
];
export default categories;
